name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: | 
          echo "${{ secrets.EC2_SECRET }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: | 
          docker buildx build --platform linux/amd64 -t shhmon/my-react-app:latest --push .

      - name: Deploy services
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "
          cd /home/ec2-user/PORTFOLIO-REACT &&
          docker-compose down &&
          docker-compose pull &&
          docker-compose up -d"